version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    command:
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      # HTTP entrypoint only
      - "--entrypoints.web.address=:80"

      # Dashboard (optional)
      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log.level=INFO"

    ports:
      - "80:80"
      - "8081:8080"   # traefik dashboard

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  app:
    build: .
    image: dingle-app
    container_name: dingle-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=8080"

    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
